os: linux
dist: bionic
language: shell

install:
  - source <(wget -O - https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/bootstrap.bash)
  - git -C ~/.tue checkout feature/ros_deps
  - tue-get install tue-documentation-github --no-ros-deps --doc-depend --branch=fix/docs
  - MSG_PKGS=($(./.ci/get_message_packages.py costmap_2d))
  - MSG_TARGETS=(${MSG_PKGS[@]/#/ros-})
  - tue-get install ros-python_orocos_kdl ${MSG_TARGETS[@]} # Needs to be installed fully as it needs to be build to generate docs
  - export ROS_PACKAGE_PATH=""

script:
  - tue-make python_orocos_kdl ${MSG_PKGS[@]} # Needs to be build to generate docs
  - source ~/.tue/setup.bash # Source the workspace
  - tue-make-documentation

before_deploy:
  - cp -r $TUE_SYSTEM_DIR/docs .

deploy:
  provider: pages
  target_branch: gh-pages-test
  skip_cleanup: true
  keep_history: false
  strategy: git
  token: $GITHUB_TOKEN
  on:
    branch: master

