os: linux
dist: bionic
language: shell

install:
  - source <(wget -O - https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/bootstrap.bash)
  - git -C ~/.tue checkout feature/ros_deps
  - tue-get install tue-documentation-github --no-ros-deps --doc-depend --branch=fix/docs
  - export ROS_PACKAGE_PATH=""

script:
  - tue-make-documentation

before_deploy:
  - cp -r $TUE_SYSTEM_DIR/docs .

deploy:
  provider: pages
  target_branch: gh-pages-test
  skip_cleanup: true
  keep_history: true
  strategy: git
  github_token: $GITHUB_TOKEN
  on:
    branch: master

