os: linux
dist: bionic
language: shell

install:
  - source <(wget -O - https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/bootstrap.bash)
  - tue-get install tue-documentation-all --doc-depend

script:
  - tue-make-documentation

before_deploy:
  - cp -r $TUE_SYSTEM_DIR/docs .

deploy:
  provider: pages
  target_branch: gh-pages-test
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: p7+QtL2fhnrjAdVaMCfrkXdd/E8Ly00KxE52b+RG6qb+vUT2QIldh2IQgnRXi3Iau9cnRw/MZ+lgyfhewRkieHOoV02b69ZMIsR91/CRYwUK4mQJtVe4Oh3HBl7oIZRNiwf5MJ+gisG4jfpURyrdkYgyf/EADOVDQe1o6uKRa9Z4DGbPdM7WLeAB87+L3zhuTPUMr+wltxBXpL7o1E2IxDH7NHVknqQyFw+XPkM7E8oEKDckqBxiHcKqotem9s5BNfYSDtPSi21h8S6gX2tELJa015whJKR4kZ5uws41+U8TzwBmJdkswEfUcCHIm3PnkvbqIZXM13HDZ/O7uE5+xGYdr+jYRM6aw53UO7S9qfyDglLf55wMPSKBMG5q2TNvJMl0wsUeKZjjrWF/sqTDXskZGcbkTYq6LrMV+cdeGcVml+ONuYLVBaZT0xJxJ1LAywtEmt0m8PV613zPCDDsjNZAMdxKHmMCnU1PAFo6Fe/M2qumK00SZQQ1rrC340NE4xhoMUQa8U+/AJgU3FmN43idGkPIXkN9DkJRjnF2t2VM5KM2sR0cO2V1r9OcO7wWe+rCuZNwb9lGyigmjXOVpSgFLxj0p9kztgTLoCyJzbB87KwUSjPT3emfe3Yo++3y2wniJllaeAoZwg/lxxGRAlNHFUhfi4sqKfp87xz0DPU=
  on:
    branch: master

