# Site settings
title: TU/e Robotics
email: techunited@tue.nl
description: > # this means to ignore newlines until "baseurl:"
  Robotics group of the TU/e (University of Technology Eindhoven). [http://www.techunited.nl/](http://www.techunited.nl/)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.techunited.nl/" # the base hostname & protocol for your site
twitter_username: TechUnited
github_username:  tue-robotics

# Build settings
markdown: kramdown
